services:
  api:
    build: ./api
    container_name: flowbit_api
    ports:
      - "4000:4000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app

  n8n:
    image: n8nio/n8n
    container_name: flowbit_n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Kolkata
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
